name: flutter_demo
description: "A new Flutter project."
publish_to: 'none' 
version: 2.1.1+7

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  shared_preferences: ^2.5.4
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true