// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDibIm2YbJGXJ-v3jgOrUWax0huw5WXxog',
    appId: '1:261183186988:web:17428b781f4181d7e54989',
    messagingSenderId: '261183186988',
    projectId: 'flutter-demo-f352a',
    authDomain: 'flutter-demo-f352a.firebaseapp.com',
    storageBucket: 'flutter-demo-f352a.firebasestorage.app',
    measurementId: 'G-DYL5799D3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN_p7o2ZqmxLnCK1U9YKGeJwp1TGYby60',
    appId: '1:261183186988:android:4e1da9741a25eb09e54989',
    messagingSenderId: '261183186988',
    projectId: 'flutter-demo-f352a',
    storageBucket: 'flutter-demo-f352a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf9lGMhFwIL1B2m8TurgT2hDDgp3oJtHU',
    appId: '1:261183186988:ios:a9dd65bdd4781d99e54989',
    messagingSenderId: '261183186988',
    projectId: 'flutter-demo-f352a',
    storageBucket: 'flutter-demo-f352a.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf9lGMhFwIL1B2m8TurgT2hDDgp3oJtHU',
    appId: '1:261183186988:ios:a9dd65bdd4781d99e54989',
    messagingSenderId: '261183186988',
    projectId: 'flutter-demo-f352a',
    storageBucket: 'flutter-demo-f352a.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDibIm2YbJGXJ-v3jgOrUWax0huw5WXxog',
    appId: '1:261183186988:web:d76b26623d67f143e54989',
    messagingSenderId: '261183186988',
    projectId: 'flutter-demo-f352a',
    authDomain: 'flutter-demo-f352a.firebaseapp.com',
    storageBucket: 'flutter-demo-f352a.firebasestorage.app',
    measurementId: 'G-EBF82L1693',
  );
}
